version: '3.9'

services:

  dbmysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: supersenha
      MYSQL_DATABASE: eulabs_db_dev
    volumes:
      - ./migrate/0001_create_db_mysql.up.sql:/docker-entrypoint-initdb.d/db.sql
      - ./tmp_data/mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - user-bridge

networks:
  user-bridge:
    name: user-bridge
